apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  labels: { app: main }
spec:
  replicas: 2
  selector:
    matchLabels: { app: main }
  template:
    metadata:
      labels: { app: main }
    spec:
      containers:
        - name: main
          image: simonxox/pathbased-web:main-1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector: { app: main }
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
